# Site settings
title: DONNEURS D'ORDRE & SOUS TRAITANTS
compagny: DOST
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog-dost-pro-btp/" # the subpath of your site, e.g. /blog/
url: "https://dost-pro.github.io" #"https://dost-pro.github.io" # the base hostname & protocol for your site
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

author: Your name

gems: [jekyll-paginate]

plugins:
  - jekyll-paginate

paginate: 4  # Number of posts per page
paginate_path: "/page:num/"
